version: '3.4'

services:
  fridge-backend:
    image: fridge-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000

  fridge-db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  fridge-db-data: